<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="38364" started-at="2016-07-24T06:19:51Z" finished-at="2016-07-24T06:20:29Z">
    <groups>
    </groups>
    <test name="testng" duration-ms="38364" started-at="2016-07-24T06:19:51Z" finished-at="2016-07-24T06:20:29Z">
      <class name="com.ultimatix.functionaltests.LaunchMultiBrowser">
        <test-method status="FAIL" signature="launch(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.ultimatix.functionaltests.LaunchMultiBrowser@91161c7]" name="launch" duration-ms="0" started-at="2016-07-24T11:49:51Z" data-provider="getData_Lauch" finished-at="2016-07-24T11:49:51Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void com.ultimatix.functionaltests.LaunchMultiBrowser.launch(java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : getData_Lauch]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void com.ultimatix.functionaltests.LaunchMultiBrowser.launch(java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : getData_Lauch
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:265)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:414)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
      </class> <!-- com.ultimatix.functionaltests.LaunchMultiBrowser -->
      <class name="com.ultimatix.functionaltests.LoginUx">
        <test-method status="PASS" signature="createScreenShotDoc()[pri:0, instance:com.ultimatix.functionaltests.LoginUx@343f4d3d]" name="createScreenShotDoc" is-config="true" duration-ms="291" started-at="2016-07-24T11:49:53Z" finished-at="2016-07-24T11:49:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createScreenShotDoc -->
        <test-method status="PASS" signature="loginUltimatix_TC01(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.ultimatix.functionaltests.LoginUx@343f4d3d]" name="loginUltimatix_TC01" duration-ms="18931" started-at="2016-07-24T11:49:53Z" data-provider="getData_LoginUx" finished-at="2016-07-24T11:50:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://www.ultimatix.net]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[roushan18]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[AUg@2016]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginUltimatix_TC01 -->
        <test-method status="PASS" signature="storeScreenShot()[pri:0, instance:com.ultimatix.functionaltests.LoginUx@343f4d3d]" name="storeScreenShot" is-config="true" duration-ms="342" started-at="2016-07-24T11:50:12Z" finished-at="2016-07-24T11:50:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- storeScreenShot -->
        <test-method status="PASS" signature="createScreenShotDoc()[pri:0, instance:com.ultimatix.functionaltests.LoginUx@343f4d3d]" name="createScreenShotDoc" is-config="true" duration-ms="2" started-at="2016-07-24T11:50:13Z" finished-at="2016-07-24T11:50:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createScreenShotDoc -->
        <test-method status="FAIL" signature="loginUltimatix_TC01(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.ultimatix.functionaltests.LoginUx@343f4d3d]" name="loginUltimatix_TC01" duration-ms="16413" started-at="2016-07-24T11:50:13Z" data-provider="getData_LoginUx" finished-at="2016-07-24T11:50:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Mozilla]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://www.ultimatix.net]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[roushan18]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[AUg@2016]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.remote.UnreachableBrowserException">
            <message>
              <![CDATA[Error communicating with the remote browser. It may have died.
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'Roushan', ip: '192.168.1.3', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_60'
Driver info: driver.version: RemoteWebDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=46.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: a043fa81-8871-445b-974c-3895a9d68691]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'Roushan', ip: '192.168.1.3', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_60'
Driver info: driver.version: RemoteWebDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=46.0.1, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: a043fa81-8871-445b-974c-3895a9d68691
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:316)
	at com.ultimatix.utils.GenericUtilLib.runBrowser(GenericUtilLib.java:147)
	at com.ultimatix.functionaltests.LoginUx.loginUltimatix_TC01(LoginUx.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:7055 [/127.0.0.1] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:162)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.execute(NewProfileExtensionConnection.java:160)
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.execute(FirefoxDriver.java:380)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 27 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	... 42 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.remote.UnreachableBrowserException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginUltimatix_TC01 -->
        <test-method status="PASS" signature="storeScreenShot()[pri:0, instance:com.ultimatix.functionaltests.LoginUx@343f4d3d]" name="storeScreenShot" is-config="true" duration-ms="65" started-at="2016-07-24T11:50:29Z" finished-at="2016-07-24T11:50:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- storeScreenShot -->
      </class> <!-- com.ultimatix.functionaltests.LoginUx -->
    </test> <!-- testng -->
  </suite> <!-- Suite -->
</testng-results>
